name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cab299e4a23a7eb189b6d48f51e74f8d99a4a06073b80d01265f5c4ca732ddb9"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
