name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd6e5275f264e88b9c603a12e1e0cbbf8e0ee3ae01b3e9f18c52b39d282b0043"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
